"""update db

Revision ID: 08e3f10776f2
Revises: 4ab25f00860d
Create Date: 2024-08-14 15:25:37.612112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e3f10776f2'
down_revision = '4ab25f00860d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
