"""update db

Revision ID: 25b5a132cd48
Revises: 818f25f8f62d
Create Date: 2024-08-15 16:55:41.134380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b5a132cd48'
down_revision = '818f25f8f62d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
