"""update db

Revision ID: 3566fb461462
Revises: aab70e3094c9
Create Date: 2024-08-13 11:38:31.683183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3566fb461462'
down_revision = 'aab70e3094c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
