"""update db

Revision ID: 4ab25f00860d
Revises: 607c53cda5c8
Create Date: 2024-08-13 15:21:28.652488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab25f00860d'
down_revision = '607c53cda5c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
