"""update db

Revision ID: 607c53cda5c8
Revises: e61b98285b86
Create Date: 2024-08-13 11:58:59.985666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607c53cda5c8'
down_revision = 'e61b98285b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_db_category_created_at'), 'db_category', ['created_at'], unique=False)
    op.create_index(op.f('ix_db_category_deleted'), 'db_category', ['deleted'], unique=False)
    op.drop_column('db_posts', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_posts', sa.Column('category', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_db_category_deleted'), table_name='db_category')
    op.drop_index(op.f('ix_db_category_created_at'), table_name='db_category')
    op.drop_table('db_category')
    # ### end Alembic commands ###
