"""update db

Revision ID: 65b905d0c58f
Revises: 08e3f10776f2
Create Date: 2024-08-14 16:05:16.932970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b905d0c58f'
down_revision = '08e3f10776f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_posts', sa.Column('category', sa.Integer(), nullable=True))
    op.add_column('db_posts', sa.Column('author', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('db_posts', 'author')
    op.drop_column('db_posts', 'category')
    # ### end Alembic commands ###
