"""update db

Revision ID: 818f25f8f62d
Revises: 65b905d0c58f
Create Date: 2024-08-15 16:42:51.466132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818f25f8f62d'
down_revision = '65b905d0c58f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
