"""update db

Revision ID: 8780546af96a
Revises: fce8bd46dfb5
Create Date: 2024-08-27 14:00:03.909252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8780546af96a'
down_revision = 'fce8bd46dfb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('project_category', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_project_created_at'), 'db_project', ['created_at'], unique=False)
    op.create_index(op.f('ix_db_project_deleted'), 'db_project', ['deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_db_project_deleted'), table_name='db_project')
    op.drop_index(op.f('ix_db_project_created_at'), table_name='db_project')
    op.drop_table('db_project')
    # ### end Alembic commands ###
