"""update db

Revision ID: aa9a63255efe
Revises: adc134ab7900
Create Date: 2024-08-20 14:43:00.920535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa9a63255efe'
down_revision = 'adc134ab7900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('db_product', 'price_sale',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('db_product', 'price_sale',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
