"""update db

Revision ID: aab70e3094c9
Revises: a6577331032b
Create Date: 2024-08-13 11:29:37.336963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aab70e3094c9'
down_revision = 'a6577331032b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_by', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_posts_created_at'), 'db_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_db_posts_deleted'), 'db_posts', ['deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_db_posts_deleted'), table_name='db_posts')
    op.drop_index(op.f('ix_db_posts_created_at'), table_name='db_posts')
    op.drop_table('db_posts')
    # ### end Alembic commands ###
