"""update db

Revision ID: ae71ec2d4d54
Revises: 3566fb461462
Create Date: 2024-08-13 11:41:32.070652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae71ec2d4d54'
down_revision = '3566fb461462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
