"""update db

Revision ID: b9dcbc3d90c6
Revises: 25b5a132cd48
Create Date: 2024-08-15 16:58:42.439609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9dcbc3d90c6'
down_revision = '25b5a132cd48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
