"""update db

Revision ID: d7e06d582e42
Revises: bb8d1d82b117
Create Date: 2024-08-20 17:10:13.801098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e06d582e42'
down_revision = 'bb8d1d82b117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
