"""update db

Revision ID: de18ac6a5e85
Revises: 20e1338ba828
Create Date: 2024-08-29 16:03:44.022572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de18ac6a5e85'
down_revision = '20e1338ba828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
