"""update db

Revision ID: e3150c44322b
Revises: b9dcbc3d90c6
Create Date: 2024-08-15 17:01:57.570744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3150c44322b'
down_revision = 'b9dcbc3d90c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
