"""update db

Revision ID: e3a6b7c33ded
Revises: e3150c44322b
Create Date: 2024-08-15 17:04:59.507774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a6b7c33ded'
down_revision = 'e3150c44322b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
