"""update db

Revision ID: e61b98285b86
Revises: ae71ec2d4d54
Create Date: 2024-08-13 11:48:24.106308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61b98285b86'
down_revision = 'ae71ec2d4d54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('db_posts', sa.Column('slug', sa.String(), nullable=False))
    op.add_column('db_posts', sa.Column('title', sa.String(), nullable=True))
    op.add_column('db_posts', sa.Column('description', sa.String(), nullable=True))
    op.add_column('db_posts', sa.Column('body', sa.String(), nullable=True))
    op.add_column('db_posts', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('db_posts', sa.Column('category', sa.Integer(), nullable=True))
    op.add_column('db_posts', sa.Column('favorited', sa.Boolean(), nullable=True))
    op.add_column('db_posts', sa.Column('favorites_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_db_posts_slug'), 'db_posts', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_db_posts_slug'), table_name='db_posts')
    op.drop_column('db_posts', 'favorites_count')
    op.drop_column('db_posts', 'favorited')
    op.drop_column('db_posts', 'category')
    op.drop_column('db_posts', 'tags')
    op.drop_column('db_posts', 'body')
    op.drop_column('db_posts', 'description')
    op.drop_column('db_posts', 'title')
    op.drop_column('db_posts', 'slug')
    # ### end Alembic commands ###
